Joss paper
YaccConstructor/LangToGroup pull request #48
Opened 2021-10-14 13:09 UTC by MaxVortman

Feel free to comment and suggest improvements

2021-10-16 10:21 UTC, gsvgit requested changes
The structure of the paper should be improved. 
1) Statement of need should be added.
2) Current "Statement of need" section should be renamed to "Solution description"
3) I guess, more discussion on the tool functionality should be added.

2021-10-16 10:21 UTC, gsvgit commented on paper/paper.md
> +  - name: Semyon Grigorev
I'm not sure that I should be the first. Project lead traditionally last in the list of authors.

2021-10-16 10:21 UTC, gsvgit commented on paper/paper.md
> +LangToGroup is a Haskell console application for group presentation construction. Haskell was chosen due to its rich and convenient type system,
It is not a statement of need. It is a solution description.

2021-10-16 10:21 UTC, gsvgit commented on paper/paper.md
> +The package provides the capability to obtain a presentation of a group from a Turing machine in two ways described in [@Sapir] and [@rotman1995word]. The algorithms to construct a Turing machine fro
This paragraph is also a solution description.

2021-10-16 10:21 UTC, gsvgit commented on paper/paper.md
> +Mainly LangToGroup package has been developed for research in disciplines such as official languages, computational theory, and group theory, but this may be of interest to researchers in many other
This one looks like a statement of need. More or less.

2021-11-11 08:13 UTC, MaxVortman commented
GitHub action for paper compilation to pdf format is added. Current version can be downloaded from "Artifacts" section at https://github.com/MaxVortman/LangToGroup/actions/runs/1447886259

2022-02-03 11:42 UTC, gsvgit approved these changes

2022-02-04 09:30 UTC, merged